### ISSUE TITLE
Merge Latest Changes

### ISSUE THREAD

**Issue by aolszowka** [comio/plex-ffmpeg#2]
Hi,

I am starting to dig down to see how difficult it would be to port in changes to support Hardware Accelerated Encoding from the Raspberry Pi.

The first step I am taking is to get to the latest version that I have been able to find from Plex which is located at https://downloads.plex.tv/ffmpeg-source/plex-media-server-ffmpeg-gpl-fa235d69f6.tar.gz

Its unclear to me though if this is the version that ships with Plex. If you want I can open up a PR that includes this change set.

**Comment by ForsakenNGS** [comment]
Do you know which ffmpeg commit this is based on? I'm currently investigating this, too. It would probably be the easiest route to start at the fork point, apply the plex changes and then merge the mainline ffmpeg changes step by step.

Edit: I mostly figured it out using the changelog, It's somewhere close after 782ae68a117f0c3611617c28eb6f5f4b9a599cfd
Edit2: Oh boy, trying to merge this with my level of ffmpeg-knowledge is going to be interesting for sure :D

**Comment by aolszowka** [comment]
@ForsakenNGS So there is an even newer version https://downloads.plex.tv/ffmpeg-source/plex-media-server-ffmpeg-gpl-b1ec5dc4b2.tar.gz

I pushed it up to my fork here: https://github.com/aolszowka/plex-ffmpeg/tree/plex-media-server-ffmpeg-gpl-b1ec5dc4b2.tar.gz

I also used the changelog to try and figure out what revision it was, I believe its around Jan 20, 2021 - 2021dbe1d6fde9259608964ef53005cde498498e opening up those two and comparing it in WinMerge showed a little more than 150 files changed between the two.

I gave up on this and am trying JellyFin now, but that's got its own barrel of problems I'm trying to work through.

**Comment by ForsakenNGS** [comment]
@aolszowka Where did you find that plex ffmpeg download link? I assume the publish the changes somewhere to conform with the license?

**Comment by aolszowka** [comment]
@ForsakenNGS In theory they do; but apparently you have to grep the Plex Pass License file for it. It looks like someone attempted to automate this process here https://github.com/Diagonactic/plex-new-transcoder but was not updated. Someone on the Plex Forms had linked this directly after performing the grep themselves, but I cannot find their original post.

Edit: Found the post https://forums.plex.tv/t/plex-media-server-1-24-6-5145-new-transcoder-preview/746527/72

**Comment by ForsakenNGS** [comment]
@aolszowka Thanks. According to my local LICENSE file the current code would be https://downloads.plex.tv/ffmpeg-source/plex-media-server-ffmpeg-gpl-62cc2bc17d.tar.gz

**Comment by ForsakenNGS** [comment]
@aolszowka I think I got hardware encoding working with a manually compiled ffmpeg-fork (original source code) and a small bash script for changing the output encoder. I've described what I did here: https://github.com/ForsakenNGS/raspi-plex-transcode/blob/main/README.md

It certainly uses the new ffmpeg executable with the new parameters and works. Performance-wise its still not ideal for my use-case, but it is certainly a starting point to get improve matters. I'll do some comparisons to the bundled encoder and try around with the settings to find out what works.
